mybatis:
  mapper-locations: classpath:mappers/*.xml
server:
  port: 8443
  servlet:
    context-path: /userdemo
    encoding:
      charset: UTF-8
spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  web:
    resources:
      static-locations: classpath:/**
  datasource:
    # -------------MSSQL-------------
#    url: jdbc:sqlserver://localhost:1433;databaseName=userDemo;TrustServerCertificate=True;encrypt=true;
#    password: "0000"
#    username: sa
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # -------------PGSQL-------------
    url: jdbc:postgresql://localhost:5432/userDemo
    password: Password
    username: demo
    driver-class-name: org.postgresql.Driver
