mybatis:
  mapper-locations: classpath:mappers/*.xml
server:
  port: 8443
  servlet:
    context-path: /userdemo
    encoding:
      charset: UTF-8
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432;databaseName=userDemo;
    password: Password
    username: demo
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
application:
  security:
    jwt:


