mybatis:
  mapper-locations: classpath:mappers/*.xml
server:
  port: 8443
  servlet:
    context-path: /userdemo
    encoding:
      charset: UTF-8
spring:
  datasource:
    # -------------MSSQL-------------
    url: jdbc:sqlserver://localhost:1433;databaseName=userDemo;TrustServerCertificate=True;encrypt=true;
    password: "0000"
    username: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # -------------PGSQL-------------
#    url: jdbc:postgresql://localhost:5432;databaseName=userDemo;
#    password: Password
#    username: demo
    #    driver-class-name: org.postgresql.Driver
