spring:
  datasource:
    url: jdbc:postgres://localhost:5432;databaseName=userDemo;TrustServerCertificate=True;encrypt=true;
    password: Password
    username: demo
    driver-class-name: com

  jpa:
      show-sql: true
      hibernate:
          auto: update

  jwt:
    secret:

