mybatis:
  mapper-locations: classpath:mappers/*.xml
server:
  port: 8443
  servlet:
    context-path: /userdemo
    encoding:
      charset: UTF-8
spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    resources:
      static-locations: classpath:/static/
  datasource:
    # -------------MSSQL-------------
    url: jdbc:sqlserver://localhost:1433;databaseName=userDemo;TrustServerCertificate=True;encrypt=true;
    password: "0000"
    username: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # -------------PGSQL-------------
#    url: jdbc:postgresql://localhost:5432/userDemo
#    password: Password
#    username: demo
#    driver-class-name: org.postgresql.Driver
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 300000 # 5min
      refresh-token:
        expiration: 300000 # 5min
